version: "2.4"

services:
  ros_ur3:
    hostname: localhost
    runtime: ${DOCKER_RUNTIME}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
              - gpu
              - utility # nvidia-smi
              - compute # CUDA. Required to avoid "CUDA version: N/A"
              - video   # NVDEC/NVENC. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need it
    privileged: true
    environment:
      # Pass host user information.
      - HOST_USER=${USER}
      - HOST_UID=1000
      - HOST_GID=1000ls
      # Display X Server GUI.
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=9.0
      - DOCKER_RUNTIME=${DOCKER_RUNTIME}
      # Needs to be explicitly define
      - ROS_HOSTNAME=localhost
      - UR3_HOME=/root/ros_ws/src/ros_ur3
      - GGCNN_HOME=/root/ros_ws/src/ros_ur3
    image: haotruongnhat/ros-ur3:noetic
    tty: true
    build:
      context: ./deep_grasp_vgu
      dockerfile: ./Dockerfile.ur3_base
      args:
        - DOCKERFILE_COMMIT_SHORT_SHA
    volumes:
      # Map ROS workspace folders.
      - D:\Projects\Deep_Grasp\deep_grasp_pybullet:/root/deep_grasp_pybullet
    network_mode: host
    command: tail -f /dev/null

