FROM nvidia/cuda:11.4.2-devel-ubuntu18.04 as base

RUN apt-get update && apt-get install -y \
      sudo \
      python-dev \
      python3-pip \
      iputils-ping \ 
      netcat \
      software-properties-common \
      git \
      tmux \
      wget \
      && \
    rm -rf /var/lib/apt/lists/*


ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

USER root
WORKDIR /root

# Install miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ./miniconda.sh
RUN chmod +x ./miniconda.sh
RUN /bin/bash -c "./miniconda.sh -b -p $HOME/miniconda"

RUN apt update && apt-get install libgl1

# Activate conda on startup
RUN /bin/bash -c 'eval "$(/root/miniconda/bin/conda shell.bash hook)" && \
                  conda create -n pybullet python==3.7 -y && \
                  conda activate pybullet && \
                  pip install numpy pybullet scikit-learn tqdm attrdict && \
                  pip install opencv-python && \
                  conda install -c pytorch pytorch'

RUN echo 'eval "$(/root/miniconda/bin/conda shell.bash hook)"' >> ~/.bashrc
RUN echo 'conda activate pybullet' >> ~/.bashrc
